### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by DaniBitZesty** [SimeonGriggs/sanity-remix-template#44]
I'm following this guide exactly https://www.sanity.io/guides/remix-run-live-preview, but I'm not able to access the env vars from projectDetails.ts without getting:

_ReferenceError: process is not defined_

And despite using:
```
 <script
  dangerouslySetInnerHTML={{
    __html: `window.ENV = ${JSON.stringify(ENV)}`,
  }}
/>
```

in root.tsx, I'm also not able to access window.ENV

_ReferenceError: window is not defined_

**Comment by SimeonGriggs** [comment]
Seems like you have a file trying access `process.env` on the client side. 

If there's a code snippet in the guide that's causing it please let me know.
