### ISSUE TITLE
Error: Named export 'Flex' not found

### ISSUE THREAD

**Issue by EdwardGoomba** [SimeonGriggs/sanity-remix-template#63]
When running a clean install - running into this error.

<img width="1920" alt="Screenshot 2024-03-16 at 12 22 23 AM" src="https://github.com/SimeonGriggs/sanity-remix-template/assets/12971857/c27a587c-5215-49fc-a678-52393775f1c8">

## Steps to Replicate
1. Follow setup steps in repo
2. Run `npm run dev`
3. Navigate to `localhost:3000` - error is thrown.

**Comment by SimeonGriggs** [comment]
Can recreate. Seeing this too, [it appears a number of packages can result in this warning](https://github.com/remix-run/remix/issues/8507).

**Comment by SimeonGriggs** [comment]
Should be resolved
