### ISSUE TITLE
Remix init script failed

### ISSUE THREAD

**Issue by wildcat63** [SimeonGriggs/sanity-remix-template#77]
For a completely fresh install, I did 
```
npx create-remix@latest --template SimeonGriggs/sanity-remix-template
```

(I'm on a MacBook Pro and running node v20.10.0)

And after answering questions on the name of the project, etc. I was asked 

```
      ◼  Running template's remix.init script...

```
Preparing Sanity Studio in /Users/[redacted]
Need to install the following packages:
sanity@3.56.0
Ok to proceed? (y)
```

And shortly after, here was the error, ending with "Oh no the Remix init script failed"

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: undefined@undefined
npm error Found: sanity@3.15.1
npm error node_modules/sanity
npm error   sanity@"3.56.0" from the root project
npm error
npm error Could not resolve dependency:
npm error sanity@"3.56.0" from the root project
npm error
npm error Conflicting peer dependency: styled-components@6.1.13
npm error node_modules/styled-components
npm error   peer styled-components@"^6.1" from sanity@3.56.0
npm error   node_modules/sanity
npm error     sanity@"3.56.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/cpardue/.npm/_logs/2024-09-01T07_58_10_479Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/cpardue/.npm/_logs/2024-09-01T07_58_10_479Z-debug-0.log

      ▲  Oh no! Template's remix.init script failed
```

It's not an urgent issue; there are plenty of other Sanity resources.  I just thought I would bring this to your attention.

**Comment by SimeonGriggs** [comment]
I've just tried the same command and not getting the same error. Even on the same version of node. If you could provide any more detail for me to reproduce would be appreciated.
